###

GET http://localhost:8080/library/


###

GET http://localhost:8080/library/1


###
POST http://localhost:8080/library/
Content-Type: application/json

{
  "name": "Monsters",
  "author": "testing author",
  "genre" : "horror"
}

###

PUT http://localhost:8080/library/2
Content-Type: application/json

{
  "name": "new updated",
  "author": "testing author",
  "genre" : "horror"
}

###

DELETE  http://localhost:8080/library/2
