GET http://localhost:8080/users/

###

POST http://localhost:8080/users/
Content-Type: application/json

{
    "id": "9",
    "name": "Felipe Connor",
    "isActive": true
}

###

GET http://localhost:8080/users/1

###
DELETE  http://localhost:8080/users/3

###

PUT  http://localhost:8080/users/2
Content-Type: application/json

{
    "name": "Felipe updated",
    "isActive": true
}