bin = "bin/main"

tmp_dir = "tmp"

[build]

cmd = "go build -o ./bin/main ./cmd"

include_ext = ["go", "tpl", "tmpl", "html", "css"]

exclude_dir = ["assets", "tmp", "bin"]

src_dir = ["cmd", "."]

[log]

level = "debug"

[run]

cmd = "./bin/main"
