version: '3.8'

services:
  # Serviço da aplicação Go
  pdfstore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - minio
    networks:
      - app-network
    env_file:
      - .env

  # Serviço do MinIO
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

# Volumes
volumes:
  minio-data: 

# Networks
networks:
  app-network:
    driver: bridge
