GET http://localhost:8080/users/

###

POST http://localhost:8080/users/
Content-Type: application/json

{
    "id": "9",
    "name": "Felipe Connor",
    "isActive": true
}

###

GET http://localhost:8080/users/6

###
DELETE  http://localhost:8080/users/3
