GET http://localhost:8000/

###

POST http://localhost:8000/car
Content-Type: application/json

{
  "name": "",
  "year": 0
}

###

POST http://localhost:8000/moto
Content-Type: application/json

{
  "name": "motoca",
  "year": 20
}

###

POST http://localhost:8000/dog
Content-Type: application/json

{
  "name": "pintado",
  "breed": "dalmata"
}


### Middlewares
GET http://localhost:8000/admin/main

### 
POST http://localhost:8000/admin/main
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "username": "felpola",
  "password": "123"
}